// The CLI must never forward a driver message, URL, credential, stack or filesystem path.
export function safeFamilyPlanError(error: unknown): string {
  const code = error && typeof error === "object" && "code" in error ? String(error.code) : "";
  const known: Record<string, string> = {
    ENOENT: "FAMILY_LOCAL_FILE_NOT_FOUND", EACCES: "FAMILY_LOCAL_FILE_ACCESS_DENIED",
    ENOTFOUND: "FAMILY_DATABASE_DNS_FAILED", ETIMEDOUT: "FAMILY_DATABASE_TIMEOUT",
    ECONNREFUSED: "FAMILY_DATABASE_CONNECTION_REFUSED", "28P01": "FAMILY_DATABASE_AUTHENTICATION_FAILED",
    "42501": "FAMILY_DATABASE_PERMISSION_DENIED", "40001": "FAMILY_CONCURRENT_CHANGE_ROLLED_BACK",
    P2034: "FAMILY_CONCURRENT_CHANGE_ROLLED_BACK", P2002: "FAMILY_UNIQUE_CONFLICT_ROLLED_BACK",
    SELF_SIGNED_CERT_IN_CHAIN: "FAMILY_DATABASE_TLS_CHAIN_FAILED",
    UNABLE_TO_VERIFY_LEAF_SIGNATURE: "FAMILY_DATABASE_TLS_CHAIN_FAILED",
    ERR_TLS_CERT_ALTNAME_INVALID: "FAMILY_DATABASE_TLS_HOSTNAME_FAILED",
  };
  if (known[code]) return known[code];
  const message = error instanceof Error ? error.message : "";
  const allowed = new Set([
    "FAMILY_PLAN_FILE_INVALID", "FAMILY_READ_ONLY_REQUIRED", "FAMILY_SCHEMA_PARTIAL_ABORTED",
    "FAMILY_SCHEMA_MISSING_PRE_MIGRATION_REQUIRED", "FAMILY_TARGET_MISMATCH", "FAMILY_MODE_MISMATCH",
    "FAMILY_EXECUTION_CONFIRMATION_REQUIRED", "FAMILY_DRY_RUN_CONFIRMATION_REJECTED",
    "FAMILY_PLAN_CONFLICTS_ABORTED", "FAMILY_WRITE_RESULT_INVALID",
    "FAMILY_PROTECTED_FIELDS_CHANGED_ABORTED", "FAMILY_FINAL_RECONCILIATION_ABORTED",
    "FAMILY_STRICT_WRITER_REQUIRED", "FAMILY_DATABASE_ROW_INVALID", "FAMILY_DATABASE_CONNECTION_FAILED",
    "PLAN_CHECKSUM_INVALID", "PLAN_CHECKSUM_MISMATCH", "PLAN_JSON_INVALID", "PLAN_SCHEMA_INVALID",
    "PLAN_EXPECTATIONS_INVALID", "PLAN_DUPLICATE_FAMILY_SLUG", "PLAN_DUPLICATE_CODE",
    "PLAN_DUPLICATE_PRODUCT_SLUG", "PLAN_FAMILY_PRODUCT_SLUG_COLLISION", "PLAN_PRODUCT_CODES_MISMATCH",
    "PLAN_DUPLICATE_VARIANT_LABEL", "PLAN_IMAGE_SELECTION_MISMATCH", "PLAN_SUMMARY_MISMATCH",
    "PLAN_EXPECTED_COUNTS_MISMATCH",
  ]);
  return allowed.has(message) ? message : "FAMILY_PLAN_VALIDATION_OR_OPERATION_FAILED";
}
