import { ArrowRight, ArrowUpRight } from "lucide-react";
import { Link } from "react-router-dom";
import { useCatalogDetail } from "../../hooks/useCatalog";

export function HeroSection() {
  const { detail } = useCatalogDetail("multifibras-orange");
  const item = detail?.item;
  return <section className="bg-[#eef3f1]"><div className="mx-auto grid max-w-[1440px] items-center gap-5 px-5 py-10 md:min-h-[500px] md:grid-cols-[1.05fr_1fr] md:px-8 md:py-12 xl:min-h-[550px] xl:px-16">
    <div className="relative z-10 min-w-0"><p className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.22em] text-[#16818f]"><span className="h-px w-8 bg-current"/>El cuidado comienza aquí</p><h1 className="mt-5 max-w-xl text-[43px] font-black leading-[1.03] tracking-[-0.06em] text-[#142f33] sm:text-6xl lg:text-[76px]">Tu espacio.<br/>Tu limpieza.<br/><span className="text-[#168fa1]">Tu Magno.</span></h1><p className="mt-6 max-w-md text-sm leading-7 text-[#445b5c] sm:text-base">Conoce nuestros productos y encuentra la presentación que estás buscando. Toda la información, en un solo lugar.</p><Link to="/productos" className="mt-7 inline-flex min-h-12 items-center gap-8 rounded-full bg-[#142f33] px-7 py-3 text-sm font-bold text-white transition hover:bg-[#168fa1]">Explorar catálogo <ArrowRight size={18}/></Link></div>
    <div className="relative mx-auto flex aspect-[1.22] w-full max-w-[570px] items-center justify-center md:aspect-square"><div aria-hidden="true" className="absolute inset-[7%] rounded-full border border-[#b5cfcb]"/><div aria-hidden="true" className="absolute inset-[16%] rounded-full bg-[#d8e7e0]"/>{item?.imageUrl ? <img src={item.imageUrl} alt={`${item.name}, presentación de referencia del catálogo`} width="560" height="560" fetchPriority="high" decoding="async" className="relative h-[85%] w-[85%] object-contain mix-blend-multiply"/> : <span className="relative text-5xl font-black tracking-tighter text-[#168fa1]">MAGNO.</span>}{item && <Link to={`/producto/${item.slug}`} className="absolute bottom-0 left-2 right-2 flex items-center justify-between gap-3 rounded-xl border border-white/90 bg-white/95 p-4 shadow-sm sm:left-8 sm:right-8"><span className="min-w-0"><span className="block text-[9px] font-bold uppercase tracking-[0.2em] text-black/40">Conoce la familia</span><span className="mt-1 block text-sm font-black text-[#142f33]">{item.name}</span><span className="mt-1 block text-xs text-black/55">{item.type === "FAMILY" ? `${item.variantCount} presentaciones para consultar` : "Consulta sus detalles"}</span></span><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#e5f1ef] text-[#16818f]"><ArrowUpRight size={21}/></span></Link>}</div>
  </div><div className="border-t border-[#c9d9d4] px-5 py-4"><div className="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-10 gap-y-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#3e5959] sm:text-xs"><span>Consulta productos</span><span aria-hidden="true" className="text-[#EF8329]">✳</span><span>Compara presentaciones</span><span aria-hidden="true" className="hidden text-[#EF8329] sm:inline">✳</span><span className="hidden sm:inline">Encuentra tu Magno</span></div></div></section>;
}
