import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowDown, ArrowLeft, ArrowUp, Check, Copy, Plus, Save, Send, Trash2, Upload } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useAdminFeedback } from "../components/admin/AdminFeedback";
import { clonePublished, createDraft, fetchWebsiteContent, payloadFromRevision, publishRevision, transitionRevision, updateDraft } from "../lib/websiteContent";
import type { ContentTargetType, RevisionPayload, WebsiteContent, WebsiteContentRevision, WebsiteContentSource } from "../types/websiteContent";

const pictograms = ["GHS01","GHS02","GHS03","GHS04","GHS05","GHS06","GHS07","GHS08","GHS09"];
const labels: Record<string,string>={GHS01:"Explosivo",GHS02:"Inflamable",GHS03:"Comburente",GHS04:"Gas a presión",GHS05:"Corrosivo",GHS06:"Toxicidad aguda",GHS07:"Irritante",GHS08:"Peligro grave para la salud",GHS09:"Peligro ambiental"};
const field="min-h-11 w-full rounded-xl border border-black/10 bg-white px-4 py-3 outline-none focus:border-[#19A2B6] focus:ring-2 focus:ring-[#19A2B6]/20 disabled:bg-black/[.03]";
const statusLabel={DRAFT:"Borrador",REVIEW:"En revisión",APPROVED:"Aprobado",PUBLISHED:"Publicado"};
const split=(value:string)=>value.split("\n").map((item)=>item.trim()).filter(Boolean);

function SourcePanel({title,source}:{title:string;source?:WebsiteContentSource}) { return <section className="min-w-0 rounded-[1.5rem] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#19A2B6]">Sólo lectura</p><h2 className="mt-1 text-xl font-black">{title}</h2></div>{source?.reviewRequired&&<span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-800">Revisión requerida</span>}</div>{source?<><p className="mt-4 break-all text-xs font-bold text-black/45">{source.sourceFile||"Fuente interna"} · Confianza {source.confidence||"sin clasificar"}</p><pre className="mt-4 max-h-[32rem] overflow-auto whitespace-pre-wrap break-words rounded-xl bg-[#F5F5F5] p-4 text-xs leading-6">{JSON.stringify(source.data,null,2)}</pre></>:<div className="mt-5 rounded-xl border border-dashed border-black/15 p-5 text-sm text-black/45">No hay información disponible en esta capa.</div>}</section>; }
function TextList({label,value,onChange,disabled=false}:{label:string;value:string[];onChange:(value:string[])=>void;disabled?:boolean}) { return <label className="grid gap-2 text-sm font-black">{label}<textarea disabled={disabled} value={value.join("\n")} onChange={(event)=>onChange(split(event.target.value))} rows={4} className={field} placeholder="Un elemento por línea"/><span className="text-xs font-medium text-black/40">Un elemento por línea.</span></label>; }

export function AdminContentEditor({type}:{type:ContentTargetType}) {
  const params=useParams(), id=String(type==="family"?params.familyId:params.productId), feedback=useAdminFeedback();
  const [content,setContent]=useState<WebsiteContent|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  const [selectedId,setSelectedId]=useState<string|null>(null),[form,setForm]=useState<RevisionPayload>(()=>payloadFromRevision(null)),[mobileTab,setMobileTab]=useState<"technical"|"derived"|"web">("web");
  const [confirmConflicts,setConfirmConflicts]=useState(false),[confirmationNote,setConfirmationNote]=useState("");
  const load=useCallback(async(preferId?:string)=>{setLoading(true);setError("");try{const result=await fetchWebsiteContent(type,id);setContent(result);const selected=result?.revisions.find((revision)=>revision.id===preferId)||result?.revisions.find((revision)=>revision.status==="DRAFT")||result?.revisions[0]||null;setSelectedId(selected?.id||null);setForm(payloadFromRevision(selected));}catch(caught){setError(caught instanceof Error?caught.message:"No se pudo cargar el contenido");}finally{setLoading(false);}},[id,type]);
  useEffect(()=>{
    // La consulta inicial carga la revisión autorizada desde la API administrativa.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  },[load]);
  const revision=useMemo(()=>content?.revisions.find((item)=>item.id===selectedId)||null,[content,selectedId]);
  const editable=revision?.status==="DRAFT";
  const technical=content?.sources.find((source)=>source.layer==="SOURCE_TECHNICAL"),derived=content?.sources.find((source)=>source.layer==="DERIVED_COMMERCIAL"),hasConflicts=Boolean(content?.sources.some((source)=>source.reviewRequired));
  const targetName=content?.family?.name||content?.product?.name||"Contenido editorial";
  function chooseRevision(item:WebsiteContentRevision){setSelectedId(item.id);setForm(payloadFromRevision(item));setConfirmConflicts(false);setConfirmationNote("");}
  async function action(run:()=>Promise<WebsiteContentRevision>,message:string){if(saving)return;setSaving(true);try{const next=await run();feedback.toast("success",message);await load(next.id);}catch(caught){feedback.toast("error",caught instanceof Error?caught.message:"No se pudo completar la acción");}finally{setSaving(false);}}
  async function save(){if(!revision)return void action(()=>createDraft(type,id,form),"Borrador creado");await action(()=>updateDraft(revision.id,form),"Borrador guardado");}
  const panelClass=(name:typeof mobileTab)=>`${mobileTab===name?"block":"hidden"} min-w-0 xl:block`;
  if(loading)return <section className="min-h-screen px-4 py-8"><div className="mx-auto max-w-7xl animate-pulse rounded-[2rem] bg-white p-10" role="status">Cargando contenido editorial…</div></section>;
  if(error)return <section className="min-h-screen px-4 py-8"><div role="alert" className="mx-auto max-w-3xl rounded-[2rem] border border-red-200 bg-red-50 p-7"><h1 className="text-2xl font-black">No pudimos abrir el editor</h1><p className="mt-2 text-red-700">{error}</p><button onClick={()=>void load()} className="mt-5 min-h-11 rounded-full bg-red-700 px-5 font-black text-white">Reintentar</button></div></section>;
  return <section className="min-h-screen px-4 py-8 sm:px-5 lg:px-8"><div className="mx-auto min-w-0 max-w-[1500px]">
    <Link to="/admin/content" className="inline-flex min-h-11 items-center gap-2 font-black text-black/55 hover:text-black"><ArrowLeft size={18}/>Volver a contenido</Link>
    <div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><p className="text-sm font-black uppercase tracking-[.22em] text-[#19A2B6]">{type==="family"?"Familia":"Producto"}</p><h1 className="mt-2 break-words text-3xl font-black tracking-[-.04em] sm:text-4xl">{targetName}</h1>{content?.product&&<p className="mt-2 break-all text-sm font-bold text-black/45">SKU {content.product.code}</p>}</div><div className="flex flex-wrap gap-2">{revision&&<span className="self-center rounded-full bg-black px-3 py-2 text-xs font-black text-white">v{revision.version} · {statusLabel[revision.status]}</span>}{!revision&&<button disabled={saving} onClick={()=>void save()} className="min-h-11 rounded-full bg-[#19A2B6] px-5 font-black text-white disabled:opacity-50"><Plus className="mr-2 inline" size={17}/>Crear borrador</button>}{revision?.status==="PUBLISHED"&&<button disabled={saving} onClick={()=>void action(()=>clonePublished(revision.id),"Nueva revisión creada")} className="min-h-11 rounded-full bg-[#111] px-5 font-black text-white disabled:opacity-50"><Copy className="mr-2 inline" size={17}/>Crear nueva versión</button>}</div></div>
    {hasConflicts&&<div role="alert" className="mt-6 flex gap-3 rounded-[1.25rem] border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle className="shrink-0" size={21}/><div><p className="font-black">Existen fuentes que requieren revisión humana</p><p className="mt-1 text-sm">La publicación requerirá confirmación explícita y una nota de justificación.</p></div></div>}
    <div className="mt-6 grid grid-cols-3 rounded-xl bg-white p-1 shadow-sm xl:hidden" role="tablist" aria-label="Capas editoriales">{([['technical','Fuente'],['derived','Derivado'],['web','Contenido web']] as const).map(([value,label])=><button key={value} role="tab" aria-selected={mobileTab===value} onClick={()=>setMobileTab(value)} className={`min-h-11 rounded-lg px-2 text-xs font-black sm:text-sm ${mobileTab===value?"bg-[#111] text-white":"text-black/50"}`}>{label}</button>)}</div>
    <div className="mt-6 grid min-w-0 gap-5 xl:grid-cols-3">
      <div className={panelClass("technical")}><SourcePanel title="Fuente técnica" source={technical}/></div>
      <div className={panelClass("derived")}><SourcePanel title="Contenido derivado" source={derived}/></div>
      <div className={panelClass("web")}><section className="min-w-0 rounded-[1.5rem] bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.18em] text-[#EF8329]">Aprobado para web</p><h2 className="mt-1 text-xl font-black">Revisión editable</h2>{revision&&!editable&&<p className="mt-3 rounded-xl bg-black/[.04] p-3 text-sm font-bold text-black/55">Esta revisión es de sólo lectura. Para modificar una publicada, crea una nueva versión.</p>}
        <div className="mt-5 grid gap-5"><label className="grid gap-2 text-sm font-black">Título<input disabled={!editable} value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} className={field}/></label><label className="grid gap-2 text-sm font-black">Descripción corta<textarea disabled={!editable} value={form.shortDescription} onChange={(e)=>setForm({...form,shortDescription:e.target.value})} rows={3} className={field}/></label><label className="grid gap-2 text-sm font-black">Descripción larga<textarea disabled={!editable} value={form.longDescription} onChange={(e)=>setForm({...form,longDescription:e.target.value})} rows={7} className={field}/></label>
          <TextList label="Beneficios" value={form.benefits} disabled={!editable} onChange={(benefits)=>setForm({...form,benefits})}/><TextList label="Aplicaciones" value={form.applications} disabled={!editable} onChange={(applications)=>setForm({...form,applications})}/><TextList label="Modo de uso" value={form.usage} disabled={!editable} onChange={(usage)=>setForm({...form,usage})}/><TextList label="Dilución" value={form.dilution} disabled={!editable} onChange={(dilution)=>setForm({...form,dilution})}/><TextList label="Precauciones" value={form.precautions} disabled={!editable} onChange={(precautions)=>setForm({...form,precautions})}/>
          <fieldset disabled={!editable}><legend className="text-sm font-black">Pictogramas GHS</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{pictograms.map((item)=><label key={item} className={`flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm font-bold ${form.pictograms.includes(item)?"border-[#19A2B6] bg-[#19A2B6]/10":"border-black/10"}`}><input type="checkbox" checked={form.pictograms.includes(item)} onChange={(e)=>setForm({...form,pictograms:e.target.checked?[...form.pictograms,item]:form.pictograms.filter((value)=>value!==item)})}/><span><strong>{item}</strong><span className="block text-xs font-medium text-black/50">{labels[item]}</span></span></label>)}</div></fieldset>
          <fieldset disabled={!editable}><legend className="text-sm font-black">Preguntas frecuentes</legend><div className="mt-2 grid gap-3">{form.faq.length===0&&<p className="rounded-xl border border-dashed border-black/15 p-4 text-sm text-black/45">Sin preguntas frecuentes.</p>}{form.faq.map((faq,index)=><div key={index} className="grid min-w-0 gap-2 rounded-xl bg-[#F5F5F5] p-3"><input aria-label={`Pregunta ${index+1}`} value={faq.question} onChange={(e)=>setForm({...form,faq:form.faq.map((item,i)=>i===index?{...item,question:e.target.value}:item)})} className={field} placeholder="Pregunta"/><textarea aria-label={`Respuesta ${index+1}`} value={faq.answer} onChange={(e)=>setForm({...form,faq:form.faq.map((item,i)=>i===index?{...item,answer:e.target.value}:item)})} rows={3} className={field} placeholder="Respuesta"/><div className="flex flex-wrap gap-2"><button type="button" aria-label="Mover pregunta arriba" disabled={index===0} onClick={()=>{const faq=[...form.faq];[faq[index-1],faq[index]]=[faq[index],faq[index-1]];setForm({...form,faq})}} className="grid min-h-11 min-w-11 place-items-center rounded-lg bg-white disabled:opacity-30"><ArrowUp size={17}/></button><button type="button" aria-label="Mover pregunta abajo" disabled={index===form.faq.length-1} onClick={()=>{const faq=[...form.faq];[faq[index+1],faq[index]]=[faq[index],faq[index+1]];setForm({...form,faq})}} className="grid min-h-11 min-w-11 place-items-center rounded-lg bg-white disabled:opacity-30"><ArrowDown size={17}/></button><button type="button" onClick={()=>setForm({...form,faq:form.faq.filter((_,i)=>i!==index)})} className="ml-auto flex min-h-11 items-center gap-2 rounded-lg bg-red-50 px-3 font-bold text-red-700"><Trash2 size={16}/>Eliminar</button></div></div>)}<button type="button" onClick={()=>setForm({...form,faq:[...form.faq,{question:"",answer:""}]})} className="min-h-11 rounded-xl border border-dashed border-black/20 font-black"><Plus className="mr-2 inline" size={17}/>Agregar pregunta</button></div></fieldset>
          <div className="border-t border-black/10 pt-5"><h3 className="font-black">SEO</h3><div className="mt-3 grid gap-4"><label className="grid gap-2 text-sm font-black">Título SEO<input disabled={!editable} value={form.seoTitle} onChange={(e)=>setForm({...form,seoTitle:e.target.value})} className={field}/></label><label className="grid gap-2 text-sm font-black">Descripción SEO<textarea disabled={!editable} value={form.seoDescription} onChange={(e)=>setForm({...form,seoDescription:e.target.value})} rows={3} className={field}/></label><TextList label="Palabras clave" value={form.seoKeywords} disabled={!editable} onChange={(seoKeywords)=>setForm({...form,seoKeywords})}/><label className="grid gap-2 text-sm font-black">URL ficha técnica<input disabled={!editable} type="url" value={form.technicalSheetUrl} onChange={(e)=>setForm({...form,technicalSheetUrl:e.target.value})} className={field}/></label><label className="grid gap-2 text-sm font-black">URL hoja de seguridad<input disabled={!editable} type="url" value={form.sdsUrl} onChange={(e)=>setForm({...form,sdsUrl:e.target.value})} className={field}/></label></div></div>
        </div>
        {editable&&<div className="sticky bottom-3 mt-6 grid gap-2 rounded-2xl border border-black/10 bg-white/95 p-3 shadow-xl backdrop-blur sm:flex sm:flex-wrap"><button disabled={saving} onClick={()=>void save()} className="min-h-11 rounded-full bg-[#111] px-5 font-black text-white disabled:opacity-50"><Save className="mr-2 inline" size={17}/>Guardar borrador</button><button disabled={saving} onClick={()=>revision&&void action(()=>transitionRevision(revision.id,"submit-review"),"Enviado a revisión")} className="min-h-11 rounded-full bg-[#19A2B6] px-5 font-black text-white disabled:opacity-50"><Send className="mr-2 inline" size={17}/>Enviar a revisión</button></div>}
        {revision?.status==="REVIEW"&&<button disabled={saving} onClick={()=>void action(()=>transitionRevision(revision.id,"approve"),"Contenido aprobado")} className="mt-6 min-h-11 w-full rounded-full bg-[#19A2B6] px-5 font-black text-white"><Check className="mr-2 inline" size={17}/>Aprobar</button>}
        {revision?.status==="APPROVED"&&<div className="mt-6 grid gap-3">{hasConflicts&&<><label className="flex min-h-11 items-center gap-3 rounded-xl bg-amber-50 p-3 text-sm font-black"><input type="checkbox" checked={confirmConflicts} onChange={(e)=>setConfirmConflicts(e.target.checked)}/>Confirmo la revisión de fuentes conflictivas</label><label className="grid gap-2 text-sm font-black">Nota de confirmación<textarea value={confirmationNote} onChange={(e)=>setConfirmationNote(e.target.value)} rows={3} className={field}/></label></>}<button disabled={saving||hasConflicts&&(!confirmConflicts||!confirmationNote.trim())} onClick={()=>void action(()=>publishRevision(revision.id,{confirmConflicts,confirmationNote}),"Contenido publicado")} className="min-h-11 rounded-full bg-emerald-600 px-5 font-black text-white disabled:opacity-40"><Upload className="mr-2 inline" size={17}/>Publicar</button></div>}
      </section></div>
    </div>
    <section className="mt-6 rounded-[1.5rem] bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Historial de revisiones</h2>{!content?.revisions.length?<p className="mt-4 text-sm text-black/45">Todavía no existen revisiones.</p>:<div className="mt-4 grid gap-2">{content.revisions.map((item)=><button key={item.id} onClick={()=>chooseRevision(item)} className={`grid min-h-14 min-w-0 gap-1 rounded-xl border p-3 text-left sm:grid-cols-[auto_1fr_auto] sm:items-center sm:gap-4 ${item.id===selectedId?"border-[#19A2B6] bg-[#19A2B6]/5":"border-black/10"}`}><span className="font-black">v{item.version}</span><span className="text-sm font-bold">{statusLabel[item.status]} · {item.createdBy.name}</span><span className="text-xs font-bold text-black/45">{new Date(item.updatedAt).toLocaleString("es-MX")}</span></button>)}</div>}</section>
    <p className="sr-only" aria-live="polite">{revision?`Revisión ${revision.version}, estado ${statusLabel[revision.status]}`:"Sin revisión seleccionada"}</p>
  </div></section>;
}
