import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";
type Customer={email:string;name:string;phone:string;orders:number;total:number;lastOrder:string};
const money=(value:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(value);
export function AdminCustomers(){
  const[customers,setCustomers]=useState<Customer[]>([]),[query,setQuery]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1);
  useEffect(()=>{const timer=setTimeout(async()=>{const response=await apiFetch(`/api/admin/customers?${new URLSearchParams({page:String(page),search:query})}`);const data=await response.json();setCustomers(data.customers||[]);setPages(data.pagination?.pages||1)},250);return()=>clearTimeout(timer)},[query,page]);
  return <section className="p-4 sm:p-5 lg:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-[#19A2B6] sm:text-sm sm:tracking-[.25em]">CRM</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Clientes</h1><label className="mt-7 grid gap-2 text-sm font-black"><span className="sr-only">Buscar clientes</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Buscar cliente, correo o teléfono" className="min-h-12 w-full rounded-2xl border-0 bg-white px-5 py-3 font-bold outline-none"/></label>
    <div className="mt-5 grid gap-3 md:hidden">{customers.map(customer=><article key={customer.email} className="min-w-0 rounded-[1.25rem] bg-white p-4"><h2 className="break-words font-black">{customer.name}</h2><p className="mt-1 break-all text-xs font-bold text-black/45">{customer.email}</p><p className="mt-1 break-words text-xs font-bold text-black/45">{customer.phone}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs font-bold text-black/45">Pedidos</dt><dd className="mt-1 font-black">{customer.orders}</dd></div><div><dt className="text-xs font-bold text-black/45">Comprado</dt><dd className="mt-1 break-all font-black">{money(customer.total)}</dd></div><div className="col-span-2"><dt className="text-xs font-bold text-black/45">Última compra</dt><dd className="mt-1 font-bold">{new Date(customer.lastOrder).toLocaleDateString("es-MX")}</dd></div></dl><Link className="mt-4 flex min-h-11 items-center justify-center rounded-full bg-[#19A2B6]/10 px-4 font-black text-[#147f8e]" to={`/admin/customers/${encodeURIComponent(customer.email)}`}>Ver cliente</Link></article>)}</div>
    <div className="mt-5 hidden overflow-x-auto rounded-[1.5rem] bg-white md:block"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b text-xs uppercase text-black/40">{["Cliente","Pedidos","Comprado","Última compra",""].map(label=><th key={label} className="p-5">{label}</th>)}</tr></thead><tbody>{customers.map(customer=><tr key={customer.email} className="border-b last:border-0"><td className="p-5"><p className="font-black">{customer.name}</p><p className="text-xs font-bold text-black/40">{customer.email} · {customer.phone}</p></td><td className="p-5 font-black">{customer.orders}</td><td className="p-5 font-black">{money(customer.total)}</td><td className="p-5 text-sm font-bold text-black/45">{new Date(customer.lastOrder).toLocaleDateString("es-MX")}</td><td className="p-5"><Link className="font-black text-[#19A2B6]" to={`/admin/customers/${encodeURIComponent(customer.email)}`}>Ver</Link></td></tr>)}</tbody></table></div>
    {!customers.length&&<p className="mt-5 rounded-2xl bg-white p-10 text-center font-bold text-black/40">No encontramos clientes</p>}
    <div className="mt-5 flex items-center justify-center gap-3 sm:justify-end"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="min-h-11 rounded-full bg-white px-4 font-black disabled:opacity-30 sm:px-5">Anterior</button><span className="py-2 font-black">{page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)} className="min-h-11 rounded-full bg-white px-4 font-black disabled:opacity-30 sm:px-5">Siguiente</button></div>
  </section>;
}
