/* eslint-disable react-hooks/set-state-in-effect */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowUp, ImagePlus, Star, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useAdminFeedback } from "../components/admin/AdminFeedback";
import { AdminPageHeader, AdminSkeleton, formatCurrency } from "../components/admin/AdminUi";
import { apiFetch } from "../lib/api";

type Image={id:string;url:string;alt?:string|null;position:number;storagePath?:string|null};
type Product={id:string;slug:string;name:string;category:string;description:string;price:number;oldPrice?:number|null;badge?:string|null;imageUrl?:string|null;images:Image[]};
type Inventory={stock:number;reservedStock:number;availableStock:number};
type Movement={id:string;type:string;quantity:number;reason?:string|null;createdAt:string};
type ProductForm={slug:string;name:string;category:string;description:string;price:string;oldPrice:string;badge:string;imageUrl:string};
const emptyForm:ProductForm={slug:"",name:"",category:"",description:"",price:"",oldPrice:"",badge:"",imageUrl:""};
async function message(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"La operación no pudo completarse");return data;}

export function AdminProductEdit(){
  const{id}=useParams();const navigate=useNavigate();const client=useQueryClient();const feedback=useAdminFeedback();
  const[form,setForm]=useState<ProductForm>(emptyForm);const[externalUrls,setExternalUrls]=useState("");const[newStock,setNewStock]=useState("");const[reason,setReason]=useState("");
  const productQuery=useQuery({queryKey:["admin-product",id],enabled:Boolean(id),queryFn:async()=>message(await apiFetch(`/api/admin/products/${id}`)) as Promise<{product:Product}>});
  const inventoryQuery=useQuery({queryKey:["admin-inventory-product",id],enabled:Boolean(id),queryFn:async()=>{const [list,moves]=await Promise.all([apiFetch(`/api/admin/inventory?search=&page=1&pageSize=100`),apiFetch(`/api/admin/inventory/${id}/movements`)]);const data=await message(list);const movements=await message(moves);return{inventory:(data.inventory||[]).find((item:Inventory&{id:string})=>item.id===id) as Inventory|undefined,movements:(movements.movements||[]) as Movement[]}}});
  const product=productQuery.data?.product;const images=product?.images||[];
  useEffect(()=>{if(!product)return;setForm({slug:product.slug,name:product.name,category:product.category,description:product.description,price:String(product.price),oldPrice:product.oldPrice?String(product.oldPrice):"",badge:product.badge||"",imageUrl:product.imageUrl||""});setExternalUrls(product.images.filter(i=>!i.storagePath).map(i=>i.url).join("\n"));},[product]);
  useEffect(()=>{if(inventoryQuery.data?.inventory)setNewStock(String(inventoryQuery.data.inventory.stock));},[inventoryQuery.data]);
  const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:["admin-product",id]}),client.invalidateQueries({queryKey:["products"]})]);};

  const saveMutation=useMutation({mutationFn:async()=>{const payload={slug:form.slug,name:form.name,category:form.category,description:form.description,price:Number(form.price),oldPrice:form.oldPrice?Number(form.oldPrice):null,badge:form.badge||null,imageUrl:form.imageUrl||null};await message(await apiFetch(`/api/products/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}));const external=externalUrls.split("\n").map(url=>url.trim()).filter(Boolean).map(url=>({url,alt:form.name}));await message(await apiFetch(`/api/admin/products/${id}/images`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({images:external})}));},onSuccess:async()=>{await refresh();feedback.toast("success","Producto actualizado correctamente");navigate("/admin/products")},onError:(error:Error)=>feedback.toast("error",error.message)});
  const uploadMutation=useMutation({mutationFn:async(file:File)=>{const body=new FormData();body.append("image",file);return message(await apiFetch(`/api/admin/products/${id}/images/upload`,{method:"POST",body}))},onSuccess:async()=>{await refresh();feedback.toast("success","Imagen subida correctamente")},onError:(error:Error)=>feedback.toast("error",error.message)});
  const primaryMutation=useMutation({mutationFn:async(imageId:string)=>message(await apiFetch(`/api/admin/products/${id}/images/${imageId}/primary`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:"{}"})),onSuccess:async()=>{await refresh();feedback.toast("success","Imagen principal actualizada")},onError:(error:Error)=>feedback.toast("error",error.message)});
  const deleteMutation=useMutation({mutationFn:async(imageId:string)=>message(await apiFetch(`/api/admin/products/${id}/images/${imageId}`,{method:"DELETE"})),onSuccess:async()=>{await refresh();feedback.toast("success","Imagen eliminada")},onError:(error:Error)=>feedback.toast("error",error.message)});
  const reorderMutation=useMutation({mutationFn:async(ids:string[])=>message(await apiFetch(`/api/admin/products/${id}/images/reorder`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageIds:ids})})),onSuccess:refresh,onError:(error:Error)=>feedback.toast("error",error.message)});
  const inventoryMutation=useMutation({mutationFn:async()=>message(await apiFetch(`/api/admin/inventory/${id}/adjust`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({newStock:Number(newStock),reason})})),onSuccess:async()=>{setReason("");await Promise.all([inventoryQuery.refetch(),client.invalidateQueries({queryKey:["products"]})]);feedback.toast("success","Inventario ajustado correctamente")},onError:(error:Error)=>feedback.toast("error",error.message)});
  const move=(index:number,direction:-1|1)=>{const next=[...images];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];reorderMutation.mutate(next.map(item=>item.id));};
  const input="rounded-2xl border border-black/10 px-5 py-4 font-semibold outline-none focus:border-[#19A2B6] focus-visible:ring-2 focus-visible:ring-[#19A2B6]/30";
  if(productQuery.isLoading)return <section className="p-8"><AdminSkeleton/></section>;
  if(productQuery.isError||!product)return <section className="p-8"><h1 className="text-3xl font-black">Producto no encontrado</h1><button type="button" onClick={()=>navigate("/admin/products")} className="mt-5 rounded-full bg-black px-5 py-3 font-black text-white">Volver</button></section>;
  return <section className="p-5 lg:p-8"><AdminPageHeader eyebrow="Catálogo" title="Editar producto"/>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_380px]">
      <div className="space-y-6"><form onSubmit={e=>{e.preventDefault();saveMutation.mutate()}} className="grid gap-5 rounded-[2rem] bg-white p-6"><div className="grid gap-5 md:grid-cols-2">
        {([['name','Nombre'],['slug','Slug'],['category','Categoría'],['badge','Badge']] as const).map(([key,label])=><label key={key} className="grid gap-2 text-sm font-black">{label}<input value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required={key!=="badge"} className={input}/></label>)}
        <label className="grid gap-2 text-sm font-black md:col-span-2">URL principal externa<input value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} className={input}/></label>
        <label className="grid gap-2 text-sm font-black">Precio<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required className={input}/></label><label className="grid gap-2 text-sm font-black">Precio anterior<input type="number" min="0" step="0.01" value={form.oldPrice} onChange={e=>setForm({...form,oldPrice:e.target.value})} className={input}/></label>
      </div><label className="grid gap-2 text-sm font-black">Descripción<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required className={`${input} min-h-32`}/></label><label className="grid gap-2 text-sm font-black">URLs externas de galería, una por línea<textarea value={externalUrls} onChange={e=>setExternalUrls(e.target.value)} className={`${input} min-h-28`}/></label><div className="flex gap-3"><button disabled={saveMutation.isPending} className="rounded-full bg-[#19A2B6] px-7 py-4 font-black text-white disabled:opacity-50">{saveMutation.isPending?"Guardando...":"Guardar cambios"}</button><button type="button" onClick={()=>navigate("/admin/products")} className="rounded-full bg-black px-7 py-4 font-black text-white">Cancelar</button></div></form>
        <article className="rounded-[2rem] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Galería</h2><p className="mt-1 text-sm text-black/45">JPEG, PNG, WEBP o AVIF · máximo 5 MB</p></div><label className={`inline-flex cursor-pointer items-center gap-2 rounded-full bg-[#19A2B6] px-5 py-3 text-sm font-black text-white ${uploadMutation.isPending?"pointer-events-none opacity-50":""}`}><ImagePlus size={18}/>{uploadMutation.isPending?"Subiendo...":"Subir imagen"}<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)uploadMutation.mutate(file);e.currentTarget.value=""}}/></label></div>
          <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{images.map((image,index)=><div key={image.id} className="rounded-2xl border border-black/10 p-3"><div className="aspect-square overflow-hidden rounded-xl bg-[#F5F5F5]"><img src={image.url} alt={image.alt||form.name} width="240" height="240" loading="lazy" decoding="async" className="h-full w-full object-contain"/></div><div className="mt-3 flex items-center justify-between"><span className="text-xs font-black text-black/45">{image.storagePath?"Supabase":"Externa"}</span><div className="flex gap-1"><button type="button" aria-label="Mover imagen arriba" disabled={index===0||reorderMutation.isPending} onClick={()=>move(index,-1)} className="rounded-full p-2 hover:bg-black/5 disabled:opacity-25"><ArrowUp size={16}/></button><button type="button" aria-label="Mover imagen abajo" disabled={index===images.length-1||reorderMutation.isPending} onClick={()=>move(index,1)} className="rounded-full p-2 hover:bg-black/5 disabled:opacity-25"><ArrowDown size={16}/></button><button type="button" aria-label="Definir como principal" disabled={primaryMutation.isPending} onClick={()=>primaryMutation.mutate(image.id)} className="rounded-full p-2 text-amber-500 hover:bg-amber-50"><Star size={16}/></button><button type="button" aria-label="Eliminar imagen" disabled={deleteMutation.isPending} onClick={()=>feedback.confirm({title:"Eliminar imagen",description:image.storagePath?"Se eliminará la imagen del producto y el archivo propio de Supabase Storage.":"Se eliminará la referencia del producto. El proveedor externo no será modificado.",destructive:true,confirmLabel:"Eliminar",action:()=>deleteMutation.mutateAsync(image.id)})} className="rounded-full p-2 text-red-500 hover:bg-red-50"><Trash2 size={16}/></button></div></div></div>)}</div>{!images.length&&<p className="mt-6 rounded-2xl bg-[#F5F5F5] p-8 text-center font-bold text-black/40">Aún no hay imágenes en la galería.</p>}</article>
      </div>
      <aside className="space-y-6"><article className="rounded-[2rem] bg-white p-6"><p className="text-xs font-black uppercase tracking-[.2em] text-[#EF8329]">Vista previa</p><div className="mt-4 aspect-square overflow-hidden rounded-[1.5rem] bg-[#F5F5F5]">{form.imageUrl?<img src={form.imageUrl} alt={form.name} width="340" height="340" decoding="async" className="h-full w-full object-contain p-4"/>:<div className="flex h-full items-center justify-center text-4xl font-black text-[#19A2B6]">MC</div>}</div><h2 className="mt-5 text-2xl font-black">{form.name}</h2><p className="mt-2 text-sm text-black/50">{form.category}</p><p className="mt-4 text-2xl font-black">{formatCurrency(Number(form.price||0))}</p></article>
        <article className="rounded-[2rem] bg-white p-6"><h2 className="text-xl font-black">Inventario</h2>{inventoryQuery.data?.inventory&&<div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs font-black">{[["Físico",inventoryQuery.data.inventory.stock],["Reservado",inventoryQuery.data.inventory.reservedStock],["Disponible",inventoryQuery.data.inventory.availableStock]].map(([label,value])=><div key={label} className="rounded-2xl bg-[#F5F5F5] p-3"><span className="block text-xl">{value}</span>{label}</div>)}</div>}<form onSubmit={e=>{e.preventDefault();feedback.confirm({title:"Confirmar ajuste de inventario",description:`La existencia física cambiará a ${newStock}. Este movimiento quedará auditado.`,confirmLabel:"Ajustar",action:()=>inventoryMutation.mutateAsync()})}} className="mt-5 grid gap-3"><label className="grid gap-2 text-sm font-black">Nueva existencia<input type="number" min="0" required value={newStock} onChange={e=>setNewStock(e.target.value)} className={input}/></label><label className="grid gap-2 text-sm font-black">Razón<input required minLength={3} value={reason} onChange={e=>setReason(e.target.value)} className={input}/></label><button disabled={inventoryMutation.isPending} className="rounded-full bg-[#EF8329] px-5 py-3 text-sm font-black text-white disabled:opacity-50">{inventoryMutation.isPending?"Ajustando...":"Ajustar inventario"}</button></form>{inventoryQuery.data?.movements.slice(0,5).map(m=><div key={m.id} className="mt-3 rounded-xl bg-[#F5F5F5] p-3 text-xs"><strong>{m.type} {m.quantity>0?"+":""}{m.quantity}</strong><p className="mt-1 text-black/45">{m.reason||"Sin nota"}</p></div>)}</article>
      </aside>
    </div>
  </section>;
}
