import { ArrowRight, ArrowUpRight } from "lucide-react";
import { Link } from "react-router-dom";
import { Seo, siteUrl } from "../components/Seo";
import { CategoriesSection } from "../components/sections/CategoriesSection";
import { FeaturedProducts } from "../components/sections/FeaturedProducts";
import { HeroSection } from "../components/sections/HeroSection";

export function Home() {
  const structured = [{ "@context": "https://schema.org", "@type": "Organization", name: "Magno Clean", url: siteUrl, logo: `${siteUrl}/favicon.svg` }, { "@context": "https://schema.org", "@type": "WebSite", name: "Magno Clean", url: siteUrl, potentialAction: { "@type": "SearchAction", target: `${siteUrl}/productos?search={search_term_string}`, "query-input": "required name=search_term_string" } }];
  return <><Seo title="Magno Clean | Soluciones profesionales de limpieza" description="Conoce el catálogo Magno Clean. Consulta productos, precios y presentaciones en un solo lugar." path="/" jsonLd={structured}/><HeroSection/><CategoriesSection/><FeaturedProducts/><section className="bg-white px-5 py-12 md:px-8 md:py-16 xl:px-12"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-[1.35fr_1fr]"><div className="min-w-0 rounded-2xl bg-[#17383c] p-7 text-white sm:p-10"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#a9d5d5]">Distintas presentaciones. Una misma familia.</p><h2 className="mt-5 max-w-lg text-3xl font-black leading-tight tracking-[-0.04em] sm:text-4xl">Elige el formato.<br/>Conoce cada detalle.</h2><p className="mt-4 max-w-md text-sm leading-7 text-white/65">Consulta precio, código e imagen de cada presentación, incluso cuando no tenga existencias.</p><Link to="/producto/multifibras-orange" className="mt-6 inline-flex min-h-12 items-center gap-6 rounded-full bg-white px-6 text-xs font-bold text-[#17383c]">Explorar MULTIFIBRAS ORANGE <ArrowUpRight size={18}/></Link></div><div className="flex min-w-0 flex-col justify-between rounded-2xl border border-[#e3e8e5] bg-[#f1f3ed] p-7 sm:p-10"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#5e7567]">Acerca de Magno Clean</p><h2 className="mt-5 text-3xl font-black leading-tight tracking-[-0.04em] text-[#17383c]">Una forma más clara<br/>de conocer la limpieza.</h2><p className="mt-4 text-sm leading-7 text-[#53675d]">Nuestra marca, nuestros productos y la información que necesitas para explorar el catálogo.</p></div><Link to="/nosotros" className="mt-6 inline-flex min-h-11 items-center gap-5 text-sm font-bold text-[#17383c]">Conócenos <ArrowRight size={18}/></Link></div></div></section></>;
}
