import { ChevronDown, Search, SlidersHorizontal, X } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useState } from "react";
import { ProductCard } from "../components/product/ProductCard";
import { Seo } from "../components/Seo";
import { useCatalog } from "../hooks/useCatalog";
import type { CatalogSort } from "../types/catalog";

const sorts: Array<{ value: CatalogSort; label: string }> = [{ value: "featured", label: "Destacados" }, { value: "name-asc", label: "Nombre A–Z" }, { value: "name-desc", label: "Nombre Z–A" }, { value: "price-asc", label: "Precio menor" }, { value: "price-desc", label: "Precio mayor" }, { value: "newest", label: "Más recientes" }, { value: "oldest", label: "Más antiguos" }];

export function Products() {
  const [params, setParams] = useSearchParams();
  const [filtersOpen, setFiltersOpen] = useState(false);
  const search = params.get("search") || "", category = params.get("category") || "", brand = params.get("brand") || "";
  const sort = (params.get("sort") || "featured") as CatalogSort;
  const page = Math.max(1, Number(params.get("page")) || 1);
  const { items, pagination, filters, loading, error, refetch } = useCatalog({ page, pageSize: 24, search, category, brand, sort });
  function update(key: string, value: string) { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.delete("page"); next.delete("focus"); setParams(next, { replace: true }); }
  const hasFilters = Boolean(search || category || brand || sort !== "featured");
  const fields = <><label className="block min-w-0"><span className="mb-2 block text-[10px] font-bold uppercase tracking-wider text-black/50">Categoría</span><select value={category} onChange={(event) => update("category", event.target.value)} className="min-h-11 w-full min-w-0 rounded-lg border border-black/10 bg-white px-3 text-xs"><option value="">Todas las categorías</option>{filters.categories.map((value) => <option key={value}>{value}</option>)}</select></label><label className="mt-5 block min-w-0"><span className="mb-2 block text-[10px] font-bold uppercase tracking-wider text-black/50">Marca</span><select value={brand} onChange={(event) => update("brand", event.target.value)} className="min-h-11 w-full min-w-0 rounded-lg border border-black/10 bg-white px-3 text-xs"><option value="">Todas las marcas</option>{filters.brands.map((value) => <option key={value}>{value}</option>)}</select></label></>;
  return <><Seo title={category ? `${category}: productos de limpieza` : search ? `Resultados para ${search}` : "Catálogo de productos"} description="Explora productos, familias y presentaciones Magno Clean. Consulta los precios y detalles del catálogo." path={category ? `/productos?category=${encodeURIComponent(category)}` : "/productos"}/><section className="bg-[#f6f8f7] px-4 pb-16 pt-6 md:px-8 xl:px-12"><div className="mx-auto max-w-7xl"><nav aria-label="Migas de pan" className="mb-6 flex gap-2 text-[11px] text-black/45"><Link to="/">Inicio</Link><span aria-hidden="true">/</span><span aria-current="page">Productos</span></nav><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#16818f]">Elige tu Magno</p><h1 className="text-3xl font-black tracking-[-0.05em] text-[#142f33] sm:text-4xl lg:text-5xl">Nuestro catálogo</h1><p className="mt-3 max-w-xl text-sm leading-6 text-black/55">Una familia, todas sus presentaciones. Explora y consulta cada detalle.</p></div><p className="text-xs font-semibold text-black/45" aria-live="polite">{loading ? "Consultando catálogo…" : `${pagination.total} ${pagination.total === 1 ? "resultado" : "resultados"}`}</p></div>
    <div className="grid min-w-0 gap-6 lg:grid-cols-[210px_minmax(0,1fr)]"><aside className="hidden min-w-0 lg:block"><div className="rounded-xl border border-black/10 bg-white p-5"><h2 className="mb-6 flex items-center gap-2 text-sm font-bold text-[#142f33]"><SlidersHorizontal size={17}/>Filtrar catálogo</h2>{fields}<p className="mt-6 border-t border-black/5 pt-5 text-[11px] leading-5 text-black/45">Las familias reúnen distintas presentaciones sin duplicarse en el catálogo.</p></div></aside>
      <div className="min-w-0"><div className="mb-5 grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_190px]"><label className="relative min-w-0"><span className="sr-only">Buscar productos</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-black/35" size={18}/><input autoFocus={params.get("focus") === "search"} value={search} onChange={(event) => update("search", event.target.value)} className="min-h-12 w-full min-w-0 rounded-lg border border-black/10 bg-white pl-11 pr-4 text-sm" placeholder="Nombre, marca o código"/></label><label className="flex min-w-0 items-center gap-2 rounded-lg border border-black/10 bg-white px-3"><span className="text-[10px] font-semibold text-black/45">Ordenar</span><select aria-label="Ordenar catálogo" value={sort} onChange={(event) => update("sort", event.target.value)} className="h-12 min-w-0 flex-1 bg-transparent text-xs font-semibold">{sorts.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div>
        <button type="button" onClick={() => setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen} aria-controls="mobile-catalog-filters" className="mb-4 flex min-h-11 w-full items-center justify-between rounded-lg border border-black/10 bg-white px-4 text-xs font-bold lg:hidden"><span className="flex items-center gap-2"><SlidersHorizontal size={17}/>Filtros</span><ChevronDown size={16}/></button>{filtersOpen && <div id="mobile-catalog-filters" className="mb-5 rounded-xl border border-black/10 bg-white p-5 lg:hidden">{fields}</div>}
        {hasFilters && <button type="button" onClick={() => setParams({}, { replace: true })} className="mb-4 inline-flex min-h-11 items-center gap-2 rounded-full bg-[#e4eeeb] px-4 text-xs font-bold text-[#16818f]">Limpiar filtros <X size={14}/></button>}
        {loading ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3" aria-label="Cargando catálogo">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-[420px] animate-pulse rounded-xl bg-white"/>)}</div> : error ? <div className="rounded-xl border border-red-100 bg-white p-7"><h2 className="text-xl font-bold">No pudimos cargar el catálogo</h2><p className="mt-3 text-sm text-black/60">{error}</p><button type="button" onClick={() => refetch()} className="mt-5 min-h-11 rounded-lg bg-[#15383c] px-5 text-sm font-bold text-white">Reintentar</button></div> : items.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <ProductCard key={`${item.type}-${item.id}`} product={item}/>)}</div> : <div className="rounded-xl bg-white px-6 py-16 text-center"><Search className="mx-auto text-[#16818f]" size={30}/><h2 className="mt-4 text-2xl font-bold">No encontramos productos</h2><p className="mt-3 text-sm text-black/55">Prueba con otro nombre, marca o código.</p><button type="button" onClick={() => setParams({}, { replace: true })} className="mt-5 min-h-11 rounded-lg bg-[#15383c] px-5 text-sm font-bold text-white">Ver todo el catálogo</button></div>}
        {!loading && !error && pagination.pages > 1 && <nav aria-label="Paginación del catálogo" className="mt-8 flex flex-wrap items-center justify-center gap-3"><button type="button" disabled={page <= 1} onClick={() => update("page", String(page - 1))} className="min-h-11 rounded-lg border border-black/15 bg-white px-4 text-xs font-bold disabled:opacity-35">Anterior</button><span className="text-xs">Página {page} de {pagination.pages}</span><button type="button" disabled={page >= pagination.pages} onClick={() => update("page", String(page + 1))} className="min-h-11 rounded-lg border border-black/15 bg-white px-4 text-xs font-bold disabled:opacity-35">Siguiente</button></nav>}
      </div>
    </div>
  </div></section></>;
}
